FROM couchbase/server:community

LABEL maintainer="gadzhiev-2019@bk.ru"

ENV CB_USERNAME=admin
ENV CB_PASSWORD=adminpassword
ENV CB_BUSKET=default
ENV CB_BUSKET_PASSWORD=busketpassword

EXPOSE 8091 8092 11210